# -*- coding: utf-8 -*-
"""Qinyi Lin - Final Project(Introduction)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XeMuztpvVxycixuigWmsyQOcAKlYDbrn

# Predicting High‑Income (> $50K) in the Adult Dataset

## Introduction to Problem & Data

#### **Problem Statement**:

Accurately classifying individuals as high‑income earners (annual income > $50,000) is pivotal not only for socioeconomic research and policy design, but also for shaping the career trajectories of students like me. As I navigate college life—juggling rigorous coursework, part‑time work, and internship applications—knowing which factors truly influence salary outcomes brings clarity to my own decision‑making. Should I invest extra time in a demanding major? Would pursuing a graduate degree or specialized certifications yield a meaningful return? This project offers data‑driven insights to answer these questions. Beyond academic fulfillment, these findings help me and my peers make data‑driven decisions about future pathways.

In this analysis, I leverage the UCI Adult dataset to build and compare classification models that predict whether an individual earns more than $50K per year based on a suite of demographic, educational, and occupational attributes. By systematically exploring and modeling these factors, I gain hands‑on experience with end‑to‑end data science workflows—skills that will bolster my resume and portfolio for future employers. More importantly, this work equips me and my peers with evidence on how investments in education, work habits, and financial decisions can translate into tangible income differences.

Concretely, my goals include:

**Identifying Key Drivers**: Uncover which attributes—such as education level, hours worked per week, or capital gains—most strongly predict high earnings. These insights can inform my decisions about double‑majoring, seeking part‑time roles, or even experimenting with small‑scale investments.

**Model Comparison**: Evaluate a variety of algorithms (Logistic Regression, Decision Trees, Random Forests, K‑Nearest Neighbors) to determine not just which predictor variables matter, but how different modeling approaches perform on realistic socio‑economic data. This deepens my understanding of algorithm strengths and limitations in a context that mirrors real‑world business analytics.

**Fairness and Equity Considerations**: Assess model performance across subgroups (gender, race, etc.) to raise awareness of potential biases—an essential perspective for any data scientist committed to ethical practice.


Through this project, I not only refine my technical skills in Python, scikit‑learn, and data visualization, model training, but also develop a richer understanding of how personal and socioeconomic choices intersect. The rest of this report details the data, analytic methods, results, and actionable next steps for translating these findings into career and financial planning strategies.

# 2. Data Description

**2.1 Source and Collection**

My analysis is grounded in the Adult dataset, originally derived from the 1994 5% Public Use Microdata Sample of the U.S. Census Bureau and made accessible by the UCI Machine Learning Repository. This rich resource comprises 48,842 anonymized records spanning 15 socioeconomic attributes—including demographics, education, work habits, and financial indicators—capturing a nuanced snapshot of the mid‑1990s American labor force.

While the dataset’s breadth enables robust modeling of income determinants, it also embodies historical biases in race, gender, and regional representation. A small fraction of entries (<1.5%) contain missing values denoted by “?”, primarily in workclass, occupation, and native‑country fields. We chose to remove these records to preserve the fidelity of categorical encodings, with the understanding that this step may underrepresent certain minority subgroups.

Data ingestion proceeded via direct CSV download from the UCI repository (https://archive.ics.uci.edu/ml/datasets/Adult). After initial validation and deduplication, I performed an 80/20 stratified split—ensuring proportional representation of the income labels—to create training and hold‑out sets. This careful curation lays the foundation for reproducible modeling and fair evaluation of classification performance.

**2.2 Attributes and Types**

The dataset includes both numerical and categorical features:

#### 2.3 Data Pre-Processing & Preliminary Examination:
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import requests
import os

pip install ucimlrepo #install the ucimlrepo package

from ucimlrepo import fetch_ucirepo

# fetch dataset
census_income = fetch_ucirepo(id=20)

# data (as pandas dataframes)
X = census_income.data.features
y = census_income.data.targets

data = pd.concat([X, y], axis=1)

# metadata
print(census_income.metadata)

# variable information
print(census_income.variables) #code extracted from the oroginal dataset to import the dataset into my code

data.info()

#since there are some missing values in the dataset, I'll replace ' ?' with NaN
data.replace(' ?', pd.NA, inplace=True)

#drop rows with missing values
data.dropna(inplace=True)

#verify no missing values remain
print(data.isnull().sum())

#drop less relevant columns (e.g., 'fnlwgt' is a sample weight)
data.drop('fnlwgt', axis=1, inplace=True)

#remove trailing periods and strip whitespace from all string columns in the DataFrame
for col in data.columns:
    if data[col].dtype == 'object':
        data[col] = data[col].str.strip().str.rstrip('.')

#verify cleaning
print(data.head())
print(data['income'].unique())  #should output ['<=50K', '>50K']

#convert income categories to numerical values (0/1)
data['income'] = data['income'].map({'<=50K': 0, '>50K': 1}).astype(int)

print(data['income'].value_counts(), "\n")

"""# **Dataset Description:**

The revised dataset comprises **48,421** adult records drawn from the 1994 U.S. Census 5% Public Use Microdata Sample. Each entry is labeled according to annual income:

**Class 0 (≤ $50 K):** 36,080 individuals

**Class 1 (> $50 K):** 11,541 individuals

In addition to the target label, there are 14 predictor variables capturing a comprehensive socioeconomic profile:

**Demographics:** age (17–90), sex, race, native country[link text](https://)

**Education:** highest level (e.g. HS‑grad, Bachelors, Doctorate)

**Employment:** workclass (Private, Government, Self‑employed, etc.), occupation, hours worked per week (1–99)

**Financial indicators:** capital‑gain (0–99,999 USD), capital‑loss (0–4,356 USD)

**Family & social:** marital status, relationship status

Missing entries (< 1.5% of rows) were removed, and the fnlwgt sample‑weight column was dropped as it does not represent an individual attribute. String values have been cleaned of trailing punctuation and whitespace, and the binary income label is encoded as 0/1 for seamless model integration. This rich mixture of demographic, educational, occupational, and financial features will serve as the basis for our classification models.
"""